#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setWallpaper() {
	# background color (fallback)
	command -v xsetroot >/dev/null && xsetroot -solid "#000000"
	# background image
	if command -v feh >/dev/null ; then
		feh --no-fehbg --bg-fill ~/.wallpaper/default || \
		feh --no-fehbg --bg-fill --recursive --randomize ~/.wallpaper || \
		echo "found no wallpapers"
	fi
}

(
	# default X env
	command -v xrdb && xrdb -merge -I$HOME ~/.Xresources

	# key mapping
	command -v setxkbmap && setxkbmap 'us(altgr-intl)'
	#command -v numlockx && numlockx
	command -v xmodmap && xmodmap ~/.Xmodmap
	#make single CAPS tap act like Esc
	command -v xcape && xcape -e 'Mode_switch=Escape'

	# start muted
	command -v amixer && amixer -q set Master 0% unmute
	command -v xset && xset b off
) >/dev/null


#export QT_QPA_PLATFORMTHEME=gtk2
export QT_STYLE_OVERRIDE=gtk2
export DE="xfce"
setWallpaper

session=${1:-i3}

case "$session" in
	i3)
		exec i3
		#exec dbus-launch --exit-with-x11 --sh-syntax ck-launch-session i3
		;;
	dwm)
		exec dwm
		;;

	# try to run it as a command
	*) exec "$@" ;;
esac
