#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f "$HOME/bin/x-init" ] && . "$HOME/bin/x-init"

# mute
command -v amixer && amixer -q set Master 0% unmute

command -v xset && xset b off

#export QT_QPA_PLATFORMTHEME=gtk2
export QT_STYLE_OVERRIDE=gtk2
export DE="xfce"

session=${1:-i3}

case "$session" in
	i3)
		exec i3
		#exec dbus-launch --exit-with-x11 --sh-syntax ck-launch-session i3
		;;
	dwm)
		exec dwm
		;;

	# try to run it as a command
	*) exec "$@" ;;
esac
